### ISSUE TITLE
New juju_grant resource (eg. for shared-ownership cross model consuming)

### ISSUE THREAD

**Issue by kot0dama** [juju/terraform-provider-juju#554] opened 2024-08-21 06:43 UTC
### Requirements

Hi,

We would need to be able to `grant consume` access on an offer in a juju model we own, for a user who runs another model which we don't own ourselves.

Please correct me if I'm wrong, but I believe the [current way to integrate a cross-model relationship](https://discourse.charmhub.io/t/introducing-the-juju-terraform-provider/6939) in current terraform provider is designed for when the terraform operator is in control of both models as we would need to declare both the `juju_offer` and the `juju_integration`. I suspect such a definition to run in the background an equivalent of `juju grant <consuming-model.owner> consume <offering-model.offer-url>`.

In our case, we would not be able to declare a `juju_integration` as we do not own the model where the offer is to be consumed.

Would it be possible to add the capability to perform updates same as what `juju grant <user> <access-level> <offer-url>` would do through the juju terraform provider?

This could be something like:
```terraform
resource "juju_offer" "postgresql_offer" {
  model            = juju_model.my_database.name
  application_name = juju_application.postgresql.name
  endpoint         = "db"
}

resource "juju_grant" "postgresql_consume" {
  user = "consuming-username"
  access_level = "consume"
  offer_url = juju_offer.postgresql_offer.url
}
```

Please let me know if anything's unclear!
Thank you!

### Urgency

Required by a customer, please add it now!

### Notes & References

Deleting such resources shall have the same effect as `juju revoke`.

**Comment by Aflynn50** [comment] 2024-08-22 15:39
Hey @kot0dama, this will prioritised in the next cycle. Would you be able to bring it up in the Canonical roadmap planning when the time comes?

**Comment by kot0dama** [comment] 2024-08-26 01:14
Sure will do, thank you!

**Comment by hmlanigan** [comment] 2024-09-05 13:12
This is a duplicate of #223

**Closed by hmlanigan** 2024-09-05 13:12 UTC
Labels: kind/feature
