### ISSUE TITLE
juju_offer is not applied due to the retrieved fully qualified model name being invalid

### ISSUE THREAD

**Issue by arturo-seijas** [juju/terraform-provider-juju#155] opened 2023-02-22 13:33 UTC
Hi,

I've run into an issue when trying to add a new juju offer. It seems like the provider is trying to retrieve the fully qualified model name incorrectly, the plan output, pasted below, looks fine.
The error does show `Error: model "stg-cos-is-devops/stg-cos-is-devops" not found (not found)` when the model name is `admin/stg-cos-is-devops`

```
juju_model.cos_lite: Refreshing state... [id=74532d63-752e-4903-8aad-04842da93897]
juju_application.alertmanager: Refreshing state... [id=stg-cos-is-devops:alertmanager]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # juju_offer.alertmanager_karma_dashboard will be created
  + resource "juju_offer" "alertmanager_karma_dashboard" {
      + application_name = "alertmanager"
      + endpoint         = "karma-dashboard"
      + id               = (known after apply)
      + model            = "admin/stg-cos-is-devops"
      + name             = (known after apply)
      + url              = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Terraform Version
Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/juju/juju v0.4.3

### Affected Resource(s)
Please list the resources as a list, for example:
- juju_offer

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "0.4.3"
    }
  }
}

resource "juju_model" "cos_lite" {
  name = "stg-cos-is-devops"
}

resource "juju_application" "alertmanager" {
  name  = "alertmanager"
  model = juju_model.cos_lite.name
  trust = true

  charm {
    name     = "alertmanager-k8s"
    channel  = "edge"
    revision = 38
  }

  units = 1
}

resource "juju_offer" "alertmanager_karma_dashboard" {
  model            = juju_model.cos_lite.name
  application_name = juju_application.alertmanager.name
  endpoint         = "karma-dashboard"
}
```

### Debug Output
https://gist.github.com/arturo-seijas/9f2904a77b11a294ff49354a67aaf8e2

### Expected Behavior
The resource should have been created

### Actual Behavior
Failure to create the resource
```
Error: model "stg-cos-is-devops/stg-cos-is-devops" not found (not found)
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

Thank you

**Comment by juanmanuel-tirado** [comment] 2023-02-22 14:06
What Juju version are you running?

**Comment by arturo-seijas** [comment] 2023-02-22 14:13
> What Juju version are you running?
Client version: 2.9.38-ubuntu-amd64
Controller version: 2.9.32

**Comment by juanmanuel-tirado** [comment] 2023-02-22 14:25
I cannot reproduce this bug with a 2.9.38 controller.
```bash
juju_29 status -m stg-cos-is-devops
Model              Controller  Cloud/Region        Version  SLA          Timestamp
stg-cos-is-devops  k8s2938     microk8s/localhost  2.9.38   unsupported  15:23:57+01:00

App           Version  Status   Scale  Charm             Channel  Rev  Address        Exposed  Message
alertmanager  0.23.0   waiting      1  alertmanager-k8s  edge      38  10.152.183.70  no       waiting for container

Unit             Workload  Agent  Address       Ports  Message
alertmanager/0*  active    idle   10.1.250.245         

Offer         Application   Charm             Rev  Connected  Endpoint         Interface        Role
alertmanager  alertmanager  alertmanager-k8s  38   0/0        karma-dashboard  karma_dashboard  provider

```

**Comment by arturo-seijas** [comment] 2023-02-22 15:31
I haven't been able to reproduce it in a clean k8s cluster either. I'm not sure about what would be the best way to proceed from here. Any suggestions?

**Comment by juanmanuel-tirado** [comment] 2023-02-22 15:45
I will assume that upgrading the controller to 2.9.38 is not a simple task. 

It could be that for some reason the model is not ready by the time terraform tries to create the resource. You can try to run the `terraform apply` step by step. First, create the model. Next, the app and the offer. Let me know how it goes.

**Comment by arturo-seijas** [comment] 2023-02-22 15:54
I'll evaluate the possibility of upgrading the controller and I'll let you know if it does work. The other resources are already created, so the model it's available.
Thank you for your help!

**Comment by juanmanuel-tirado** [comment] 2023-02-23 08:24
I will close this issue. Feel free to reopen if this problem persists.

**Closed by juanmanuel-tirado** 2023-02-23 08:24 UTC
