### ISSUE TITLE
Inconsistent Result Error When Applying Changes to juju_application.ceph-mon

### ISSUE THREAD

**Issue by mateofloreza** [juju/terraform-provider-juju#380] opened 2024-01-10 15:43 UTC
### Description

Upon applying changes using Terraform for the deployment of ceph-osd and ceph-mon, an error occurred regarding inconsistent results produced by the provider. The error message displayed:

`juju_model.ceph: Creating...
juju_model.ceph: Creation complete after 2s [id=51bd3109-1463-4c3d-8962-f17f5eca6d8b]
juju_ssh_key.mykey: Creating...
juju_application.ceph-mon: Creating...
juju_application.ceph-osd: Creating...
juju_ssh_key.mykey: Creation complete after 0s [id=sshkey:ceph:ubuntu@gitlab]
juju_application.ceph-osd: Creation complete after 3s [id=ceph:ceph-osd]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to juju_application.ceph-mon, provider "provider[\"registry.terraform.io/juju/juju\"]" produced an unexpected new value:
│ .placement: was cty.StringVal("lxd:0,lxd:1,lxd:2"), but now cty.StringVal("0/lxd/0").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.`

### Urgency

Blocker for our release

### Terraform Juju Provider version

0.10.0

### Terraform version

1.6.6

### Terraform Configuration(s)

```terraform
main.tf:

terraform {
  required_providers {
    juju = {
      version = "~> 0.10.0"
      source  = "juju/juju"
    }
  }
}

provider "juju" {}

resource "juju_model" "ceph" {
    name = "ceph"

    cloud {
        name = var.juju_maas_cloud_name
        region = var.juju_maas_cloud_region
    }
}

resource "juju_application" "ceph-osd" {
    name = "ceph-osd"
    model = juju_model.ceph.name
    charm {
        name = "ceph-osd"
	    channel = "quincy/stable"
	    revision = 576
    }
    units = var.ceph_units
    constraints = var.ceph_tag
    config = var.ceph_osd_config
}

resource "juju_ssh_key" "mykey" {
    model = juju_model.ceph.name
    payload = var.juju_ssh_key
}

resource "juju_application" "ceph-mon" {
    name = "ceph-mon"
    model = juju_model.ceph.name
    charm {
        name = "ceph-mon"
	channel = "quincy/stable"
	revision = 191
    }
    units = var.ceph_units
    placement = "lxd:0,lxd:1,lxd:2"
}

.tfvars

juju_maas_cloud_name = "maas"
juju_maas_cloud_region = "default"
ceph_tag = "arch=amd64 tags=ceph"
ceph_osd_config = {
    osd-devices = "/dev/disk/by-dname/sdb"
    aa-profile-mode = "complain"
    autotune = "false"
    bluestore = "true"
    bluestore-compression-mode = "none"
    customize-failure-domain = "false"
}

ceph_units = 3

juju_ssh_key = ""

variable.tf:

variable "juju_maas_cloud_name" {
    description = "MAAS Name"
    type=string
}

variable "juju_maas_cloud_region" {
    description = "MAAS region"
    type=string
}

variable "ceph_tag" {
    description = "Ceph tag constraints"
    type = string
}

variable "ceph_osd_config" {
    description = "Ceph OSD configuration"
    type = map(string)
}

variable ceph_units {
    description = "Number of units for Ceph"
    type = number
}

variable juju_ssh_key {
    description = "SSH key to login in the machines"
    type = string
}
```

### Reproduce / Test

```shell
terraform init && terraform apply
```

### Debug/Panic Output

```shell
juju_model.ceph: Creating...
juju_model.ceph: Creation complete after 2s [id=51bd3109-1463-4c3d-8962-f17f5eca6d8b]
juju_ssh_key.mykey: Creating...
juju_application.ceph-mon: Creating...
juju_application.ceph-osd: Creating...
juju_ssh_key.mykey: Creation complete after 0s [id=sshkey:ceph:ubuntu@gitlab]
juju_application.ceph-osd: Creation complete after 3s [id=ceph:ceph-osd]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to juju_application.ceph-mon, provider "provider[\"registry.terraform.io/juju/juju\"]" produced an unexpected new value:
│ .placement: was cty.StringVal("lxd:0,lxd:1,lxd:2"), but now cty.StringVal("0/lxd/0").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by hmlanigan** [comment] 2024-01-11 14:01
This is a duplicate of issue #182.

We are planning schema changes to properly resolve this issue. The current schema conflates juju placement with juju machines.

**Closed by hmlanigan** 2024-01-11 14:01 UTC
Labels: bug, duplicate, main
