### ISSUE TITLE
terraform destroy doesn't wait for application destruction and doesn't have an option to specify --force --no-wait

### ISSUE THREAD

**Issue by dparv** [juju/terraform-provider-juju#642] opened 2024-12-10 12:13 UTC
### Requirements

```terraform
Currently the terraform apply does wait for some things like storage to be created - which is great, but the terraform destroy doesn't wait, just send the commands to the controller and exits as completed, while some applications are stuck in error and can't be destroyed.

One thing that would be good is to add the waiting for the application removal.

Also it would be good to add a parameter on the application / model resource, something like force_on_destroy true/false and/or nowait_on_destroy: true/false that will allow the pipeline to run juju remove-model --force and --no-wait in those errored out cases.
```

### Urgency

Casually wishlisting

**Comment by hmlanigan** [comment] 2024-12-19 20:10
Duplicate of #521

**Comment by alesstimec** [comment] 2024-12-20 07:51
As @hmlanigan pointed out this feature is out of scope of the terraform provider. If issues occur, those should be addressed by charm authors or juju developers. The terraform provider should not use the `--force` flag as it might leave the model in an undesirable state for future use.

**Closed by alesstimec** 2024-12-20 07:51 UTC
Labels: state/will-not-fix, kind/feature

**Comment by hloeung** [comment] 2025-02-05 02:53
Having an option to use `--force` would give us the ability to work around these known issues, and of course, disable when bugs are deemed fix.

As it is right now, when we decommission environments via Terraform, we have to manually go through cleaning up units stuck. It's not a good experience.

We also have environments using older Juju controllers which we would like to just tear down gracefully without having us perform manual things to get things going.
