### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by duythien** [juju/terraform-provider-juju#412] opened 2024-02-26 08:36 UTC
### Description

Hello
When I try to deploy kafka via example https://github.com/canonical/kafka-bundle/tree/main/terraform

### Urgency

Impacting a customer, please help now!

### Terraform Juju Provider version

v0.10.1

### Terraform version

v1.7.4

### Terraform Configuration(s)

```terraform
resource "juju_application" "kafka" {
  depends_on = [juju_machine.kafka]
  model      = juju_model.kafka.name

  units = var.kafka.units

  charm {
    name    = "kafka"
    channel = var.kafka.channel
    base    = var.kafka.base
  }

  placement = join(",", juju_machine.kafka[*].machine_id)

  config = var.kafka.config
}

resource "juju_application" "zookeeper" {
  depends_on = [juju_machine.zookeeper]
  model      = juju_model.kafka.name

  units = var.zookeeper.units

  charm {
    name    = "zookeeper"
    channel = var.zookeeper.channel
    base    = var.zookeeper.base
  }

  placement = join(",", juju_machine.zookeeper[*].machine_id)

  config = var.zookeeper.config
}


resource "juju_integration" "kafka_zookeeper" {
  model = juju_model.kafka.name

  application {
    name = juju_application.kafka.name
  }

  application {
    name = juju_application.zookeeper.name
  }
}```
```

### Reproduce / Test

```shell
juju_machine.zookeeper[1]: Creation complete after 0s [id=kafka:3:zookeeper-1]
juju_application.zookeeper: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to juju_application.zookeeper, provider "provider[\"registry.terraform.io/juju/juju\"]" produced an
│ unexpected new value: .placement: was cty.StringVal("0,3,1"), but now cty.StringVal("").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to juju_application.kafka, provider "provider[\"registry.terraform.io/juju/juju\"]" produced an
│ unexpected new value: .placement: was cty.StringVal("2"), but now cty.StringVal("").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

```
```


### Debug/Panic Output



### Notes & References

I guess the problem this line `  placement = join(",", juju_machine.kafka[*].machine_id)`

**Comment by cderici** [comment] 2024-02-28 16:28
This seems like a duplicate of #376, thanks for reporting @duythien

**Closed by cderici** 2024-02-28 16:28 UTC
Labels: bug, duplicate
