### ISSUE TITLE
Error when updating number of units

### ISSUE THREAD

**Issue by shundezhang** [juju/terraform-provider-juju#574] opened 2024-09-12 07:44 UTC
### Description

I updated the number of units of an application from 1 to 2.
After running terraform apply, I got the following error. 
```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to juju_application.kubernetes_worker, provider "provider[\"registry.terraform.io/juju/juju\"]" produced an unexpected new value: .placement: was cty.StringVal("1"), but now cty.StringVal("1,2").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```
However I can see in juju status that the new machine is created and the application is installed on it.

### Urgency

Annoying bug in our test suite

### Terraform Juju Provider version

0.13.0

### Terraform version

1.9.5

### Juju version

3.5.2

### Terraform Configuration(s)

```terraform
resource "juju_application" "kubernetes_worker" {
  name  = "kubernetes-worker"
  model = juju_model.k8s_calico.name

  charm {
    name    = "kubernetes-worker"
    channel = "1.28/stable"
    base = "ubuntu@20.04"
  }

  config = {
    kubelet-extra-config = "{}"
  }
  units = 2

}
```

### Reproduce / Test

```shell
terraform apply
```

**Comment by Aflynn50** [comment] 2024-09-12 15:36
Hey @shundezhang, this is the same bug as #443 (though slightly different way of triggering it).

**Comment by Aflynn50** [comment] 2024-09-12 15:38
Duplicate of #443

**Comment by Aflynn50** [comment] 2024-09-12 15:39
Duplicate of #443

**Closed by Aflynn50** 2024-09-12 15:39 UTC
Labels: kind/bug, area/machine
